# Generated by Django 4.0.1 on 2022-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BVNVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, choices=[('MIP', 'My Identity Pass')], max_length=25)),
                ('bvn', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_of_birth', models.DateField(null=True)),
                ('api_responses', models.ManyToManyField(blank=True, related_name='bvnverification_api_responses_set', to='utilities.APIResponse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
