# Generated by Django 4.0.1 on 2022-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvnverification',
            name='provider',
            field=models.CharField(blank=True, choices=[('MIP', 'My Identity Pass'), ('SI', 'Smile Identity')], max_length=25),
        ),
    ]
