# Generated by Django 4.0.1 on 2022-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProviderAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('MIP', 'My Identity Pass')], max_length=25)),
                ('api_key', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
