# Generated by Django 4.0.1 on 2022-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproviderapikey',
            name='api_key',
            field=models.CharField(max_length=500),
        ),
    ]
