# Generated by Django 4.0.1 on 2022-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_clientproviderapikey_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproviderapikey',
            name='provider',
            field=models.CharField(choices=[('MIP', 'My Identity Pass'), ('SI', 'Smile Identity')], max_length=25),
        ),
    ]
