# Generated by Django 4.0.1 on 2022-01-30 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(editable=False, max_length=255)),
                ('method', models.CharField(editable=False, max_length=7)),
                ('data', models.TextField(blank=True, editable=False)),
                ('response', models.TextField(editable=False)),
                ('status_code', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
