SMILE_IDENTITY_API_URL = 'https://api.smileidentity.com/v2/verify/'
SMILE_CLIENT_ID = '1186'
SMILE_COUNTRY_CODE = 'NG'
SMILE_RESULT_CODE_VALID = '1012'
SMILE_RESULT_CODE_INVALID_ID = ['1013', '1014']
SMILE_RESULT_CODE_SYSTEM_ERROR = ['1015', '1016']
SMILE_BVN_RESULT_CODE_VALID = ['1020', '1021']
SMILE_BVN_RESULT_CODE_INVALID_ID = ['1022', '1013', '1014']

SMILE_BVN_STATUS_NO_MATCH = 'no match'
SMILE_BVN_STATUS_EXACT_MATCH = 'exact match'
SMILE_BVN_STATUS_PARTIAL_MATCH = 'partial match'
SMILE_BVN_STATUS_TRANSPOSED_MATCH = 'transposed'
