PROVIDER_MY_IDENTITY_PASS = "MIP"
PROVIDER_SMILE_IDENTITY = "SI"
PROVIDERS = (
    (PROVIDER_MY_IDENTITY_PASS, 'My Identity Pass'),
    (PROVIDER_SMILE_IDENTITY, 'Smile Identity'),
)

VALID_BVN_PROVIDERS_LIST = [PROVIDER_MY_IDENTITY_PASS, PROVIDER_SMILE_IDENTITY]
